### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by whirka** [joeshaw/myq#1]
Recently I've been getting a 400 error. Wondering if this is just my account or due to some recent changes MyQ has made?

**Comment by joeshaw** [comment]
I'm seeing it too.  I'll investigate, they may have changed the protocol.

**Comment by joeshaw** [comment]
I just pushed code to update to the latest API version and the CLI is working again for me.  Try it out and let me know how it goes!

**Comment by whirka** [comment]
This is perfect. Thanks for such a quick turn-around on this!
